{{- if .Values.secretProvider.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "new-look-crud.name" . }}-kv-secrets
spec:
  provider: azure
  secretObjects:
  - secretName: {{ include "new-look-crud.name" . }}-secrets
    type: Opaque
    data: 
    - objectName:  {{ .Values.secretProvider.keyVaultName }}-AMPLIENCE-API-URI
      key:  {{ .Values.secretProvider.keyVaultName }}-AMPLIENCE-API-URI
    - objectName:  {{ .Values.secretProvider.keyVaultName }}-CONTENT-STACK-API-BASE-URI
      key:  {{ .Values.secretProvider.keyVaultName }}-CONTENT-STACK-API-BASE-URI
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretProvider.userAssignedIdentityID }}
    keyvaultName: {{ .Values.secretProvider.keyVaultName }}
    objects:  |
      array:
        - |
          objectName:  {{ .Values.secretProvider.keyVaultName }}-AMPLIENCE-API-URI
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.secretProvider.keyVaultName }}-CONTENT-STACK-API-BASE-URI
          objectType: secret
          objectVersion: ""
    
    tenantId: {{ .Values.secretProvider.tenantId }}
    subscriptionId: {{ .Values.secretProvider.subscriptionId }}
{{- end }}
