apiVersion: v1
kind: Service
metadata:
  name: {{ include "new-look-crud.fullname" . }}
  labels:
    {{- include "new-look-crud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port:  {{ .Values.service.httpsport }}
      protocol: TCP
      targetPort: http
      name: https
  selector:
    {{- include "new-look-crud.selectorLabels" . | nindent 4 }}
