
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    acme.cert-manager.io/http01-edit-in-place: 'true'
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: dev-fabric-nl.aks
      paths:
        - path: /
          pathType: Prefix

  tls: 
   - secretName: dev-fabric-nl-tls
     hosts:
       - dev-fabric-nl.aks
