
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    acme.cert-manager.io/http01-edit-in-place: 'true'
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: e2e-fabric-do.dcp-np.newlook.cloud
      paths:
        - path: /
          pathType: Prefix

  tls:
   - secretName:  e2e-fabric-do-tls
     hosts:
       - e2e-fabric-do.dcp-np.newlook.cloud

