
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    acme.cert-manager.io/http01-edit-in-place: 'true'
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: nl-crud-dev.dcp-np.newlook.cloud
      paths:
        - path: /
          pathType: Prefix

  tls: 
   - secretName: dev-fabric-do-tls
     hosts:
       - nl-crud-dev.dcp-np.newlook.cloud
